package com.example.blueridgefinalprojectapp.components

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.material.Button
import androidx.compose.material.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier

@Composable
fun AIDisclaimer() {
    var visible by remember {
        mutableStateOf(true)
    }
    AnimatedVisibility(visible = visible) {
        Row {
            Text(
                "Demo content generated by AI",
                modifier = Modifier.weight(1f)
            )
            Button(
                onClick = {visible = false}
            ) {
                Text("X")
            }
        }
    }
}